// Mock data for bills
export const mockBills = [
  {
    id: '1',
    billNumber: 'WTR-2024-001',
    service: 'Water Bill',
    amount: 15000,
    status: 'paid',
    dueDate: '2024-01-15',
    date: '2024-01-10',
    customerName: 'John Doe',
  },
  {
    id: '2',
    billNumber: 'SEC-2024-002',
    service: 'Security Services',
    amount: 25000,
    status: 'pending',
    dueDate: '2024-01-20',
    date: '2024-01-15',
    customerName: 'Jane Smith',
  },
  {
    id: '3',
    billNumber: 'SAN-2024-003',
    service: 'Sanitation',
    amount: 10000,
    status: 'overdue',
    dueDate: '2024-01-10',
    date: '2024-01-05',
    customerName: 'Bob Johnson',
  },
  {
    id: '4',
    billNumber: 'WTR-2024-004',
    service: 'Water Bill',
    amount: 18000,
    status: 'paid',
    dueDate: '2024-01-25',
    date: '2024-01-20',
    customerName: 'Alice Brown',
  },
  {
    id: '5',
    billNumber: 'SEC-2024-005',
    service: 'Security Services',
    amount: 30000,
    status: 'pending',
    dueDate: '2024-01-30',
    date: '2024-01-25',
    customerName: 'Charlie Wilson',
  },
];

// Mock statistics
export const mockStatistics = {
  totalBills: 150,
  pendingBills: 25,
  paidBills: 125,
  overdueBills: 10,
  totalRevenue: 2500000, // in RWF
  activeUsers: 1200,
  collectionRate: 85,
};

// Mock users for admin/superadmin
export const mockUsers = [
  {
    id: '1',
    username: 'john_doe',
    email: 'john@example.com',
    firstName: 'John',
    lastName: 'Doe',
    phoneNumber: '+250788123456',
    roles: ['ROLE_USER'],
    district: 'Kigali',
    sector: 'Nyarugenge',
    status: 'active',
  },
  {
    id: '2',
    username: 'jane_smith',
    email: 'jane@example.com',
    firstName: 'Jane',
    lastName: 'Smith',
    phoneNumber: '+250788654321',
    roles: ['ROLE_USER'],
    district: 'Gasabo',
    sector: 'Gisozi',
    status: 'active',
  },
  {
    id: '3',
    username: 'admin_user',
    email: 'admin@example.com',
    firstName: 'Admin',
    lastName: 'User',
    phoneNumber: '+250788111111',
    roles: ['ROLE_ADMIN'],
    district: 'Kicukiro',
    sector: 'Gatenga',
    status: 'active',
  },
  {
    id: '4',
    username: 'super_admin',
    email: 'superadmin@example.com',
    firstName: 'Super',
    lastName: 'Admin',
    phoneNumber: '+250788000000',
    roles: ['ROLE_SUPERADMIN'],
    district: 'Kigali',
    sector: 'Nyarugenge',
    status: 'active',
  },
];
